// Mock Data for Grand Zawiyah API
// This provides realistic mock data for development and testing

import { User, Donation, DonationCampaign, Event, Lesson, DonationAnalytics } from '@/types/api';

export const mockData = {
  users: [
    {
      id: 'user_1',
      email: 'demo@example.com',
      name: 'Demo User',
      phone: '+1 (555) 123-4567',
      isEmailVerified: true,
      createdAt: '2024-01-01T00:00:00Z',
      lastLoginAt: new Date().toISOString(),
      preferences: {
        notifications: true,
        newsletter: true,
        language: 'en',
        timezone: 'America/New_York',
        privacy: {
          showDonations: true,
          showProfile: false,
        },
      },
      profile: {
        bio: 'Passionate about community service and Islamic education',
        location: 'New York, NY',
        website: 'https://example.com',
        socialLinks: {
          twitter: '@demouser',
          linkedin: 'demouser',
        },
        interests: ['Education', 'Community Service', 'Spiritual Growth'],
        volunteerInterests: ['Teaching', 'Event Organization', 'Fundraising'],
      },
    },
    {
      id: 'user_2',
      email: 'john.doe@example.com',
      name: 'John Doe',
      phone: '+1 (555) 987-6543',
      isEmailVerified: true,
      createdAt: '2024-01-15T00:00:00Z',
      lastLoginAt: new Date().toISOString(),
      preferences: {
        notifications: false,
        newsletter: true,
        language: 'en',
        timezone: 'America/Los_Angeles',
        privacy: {
          showDonations: false,
          showProfile: true,
        },
      },
      profile: {
        bio: 'Software engineer and community volunteer',
        location: 'Los Angeles, CA',
        socialLinks: {},
        interests: ['Technology', 'Community Service'],
        volunteerInterests: ['Technical Support', 'Event Planning'],
      },
    },
  ] as User[],

  donations: [
    {
      id: 'donation_1',
      userId: 'user_1',
      amount: 100,
      currency: 'USD',
      frequency: 'one-time' as const,
      campaign: 'Grand Zawiyah Construction',
      status: 'completed' as const,
      paymentMethodId: 'pm_1',
      isAnonymous: false,
      message: 'May Allah accept this donation',
      createdAt: '2024-01-15T10:30:00Z',
      updatedAt: '2024-01-15T10:30:00Z',
      receiptUrl: '/receipts/donation_1.pdf',
      metadata: {
        source: 'website',
        campaignId: 'campaign_1',
      },
    },
    {
      id: 'donation_2',
      userId: 'user_1',
      amount: 50,
      currency: 'USD',
      frequency: 'monthly' as const,
      campaign: 'Islamic Education Fund',
      status: 'completed' as const,
      paymentMethodId: 'pm_1',
      isAnonymous: false,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z',
      receiptUrl: '/receipts/donation_2.pdf',
      metadata: {
        source: 'website',
        campaignId: 'campaign_2',
        recurring: true,
      },
    },
    {
      id: 'donation_3',
      userId: 'user_2',
      amount: 250,
      currency: 'USD',
      frequency: 'one-time' as const,
      campaign: 'Community Support',
      status: 'completed' as const,
      paymentMethodId: 'pm_2',
      isAnonymous: true,
      createdAt: '2024-01-20T14:15:00Z',
      updatedAt: '2024-01-20T14:15:00Z',
      receiptUrl: '/receipts/donation_3.pdf',
      metadata: {
        source: 'mobile_app',
        campaignId: 'campaign_3',
      },
    },
  ] as Donation[],

  campaigns: [
    {
      id: 'campaign_1',
      name: 'Grand Zawiyah Construction',
      description: 'Building the main zawiyah for community gatherings and education',
      goal: 500000,
      raised: 125000,
      currency: 'USD',
      startDate: '2024-01-01T00:00:00Z',
      endDate: '2024-12-31T23:59:59Z',
      status: 'active' as const,
      imageUrl: '/images/campaigns/zawiyah-construction.jpg',
      category: 'Infrastructure',
      tags: ['Construction', 'Community', 'Education'],
      donorCount: 234,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-20T00:00:00Z',
    },
    {
      id: 'campaign_2',
      name: 'Islamic Education Fund',
      description: 'Supporting online and in-person Islamic education programs',
      goal: 100000,
      raised: 45000,
      currency: 'USD',
      startDate: '2024-01-01T00:00:00Z',
      endDate: '2024-06-30T23:59:59Z',
      status: 'active' as const,
      imageUrl: '/images/campaigns/education-fund.jpg',
      category: 'Education',
      tags: ['Education', 'Online Learning', 'Scholarship'],
      donorCount: 156,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-20T00:00:00Z',
    },
    {
      id: 'campaign_3',
      name: 'Community Support',
      description: 'Helping families in need within our global community',
      goal: 150000,
      raised: 78000,
      currency: 'USD',
      startDate: '2024-01-01T00:00:00Z',
      endDate: '2024-08-31T23:59:59Z',
      status: 'active' as const,
      imageUrl: '/images/campaigns/community-support.jpg',
      category: 'Charity',
      tags: ['Charity', 'Family Support', 'Emergency Relief'],
      donorCount: 189,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-20T00:00:00Z',
    },
  ] as DonationCampaign[],

  events: [
    {
      id: 'event_1',
      title: 'Weekly Friday Prayer',
      description: 'Join us for our weekly Friday prayer service',
      startDate: '2024-01-26T13:00:00Z',
      endDate: '2024-01-26T14:00:00Z',
      location: {
        name: 'Grand Zawiyah',
        address: '123 Main Street',
        city: 'New York',
        state: 'NY',
        zipCode: '10001',
        country: 'USA',
        coordinates: {
          lat: 40.7128,
          lng: -74.0060,
        },
      },
      isVirtual: false,
      capacity: 200,
      registeredCount: 45,
      price: 0,
      currency: 'USD',
      category: 'Religious',
      tags: ['Prayer', 'Community', 'Weekly'],
      imageUrl: '/images/events/friday-prayer.jpg',
      status: 'published' as const,
      organizerId: 'user_1',
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-20T00:00:00Z',
    },
    {
      id: 'event_2',
      title: 'Islamic History Workshop',
      description: 'Learn about the rich history of Islamic civilization',
      startDate: '2024-02-10T10:00:00Z',
      endDate: '2024-02-10T16:00:00Z',
      location: {
        name: 'Community Center',
        address: '456 Oak Avenue',
        city: 'New York',
        state: 'NY',
        zipCode: '10002',
        country: 'USA',
      },
      isVirtual: true,
      virtualLink: 'https://zoom.us/j/123456789',
      capacity: 50,
      registeredCount: 23,
      price: 25,
      currency: 'USD',
      category: 'Education',
      tags: ['History', 'Workshop', 'Learning'],
      imageUrl: '/images/events/history-workshop.jpg',
      status: 'published' as const,
      organizerId: 'user_2',
      createdAt: '2024-01-15T00:00:00Z',
      updatedAt: '2024-01-20T00:00:00Z',
    },
    {
      id: 'event_3',
      title: 'Community Iftar',
      description: 'Join us for a community iftar during Ramadan',
      startDate: '2024-03-15T18:30:00Z',
      endDate: '2024-03-15T20:30:00Z',
      location: {
        name: 'Grand Zawiyah',
        address: '123 Main Street',
        city: 'New York',
        state: 'NY',
        zipCode: '10001',
        country: 'USA',
      },
      isVirtual: false,
      capacity: 150,
      registeredCount: 89,
      price: 15,
      currency: 'USD',
      category: 'Community',
      tags: ['Ramadan', 'Iftar', 'Community'],
      imageUrl: '/images/events/community-iftar.jpg',
      status: 'published' as const,
      organizerId: 'user_1',
      createdAt: '2024-01-20T00:00:00Z',
      updatedAt: '2024-01-20T00:00:00Z',
    },
  ] as Event[],

  lessons: [
    {
      id: 'lesson_1',
      title: 'Introduction to Islamic Beliefs',
      description: 'A comprehensive introduction to the fundamental beliefs of Islam',
      content: 'This lesson covers the six pillars of faith in Islam...',
      videoUrl: 'https://example.com/videos/lesson1.mp4',
      audioUrl: 'https://example.com/audio/lesson1.mp3',
      duration: 45,
      difficulty: 'beginner' as const,
      category: 'Aqeedah',
      tags: ['Beliefs', 'Fundamentals', 'Aqeedah'],
      isPremium: false,
      instructorId: 'instructor_1',
      instructorName: 'Shaykh Ahmad Hassan',
      thumbnailUrl: '/images/lessons/lesson1-thumb.jpg',
      publishedAt: '2024-01-01T00:00:00Z',
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z',
    },
    {
      id: 'lesson_2',
      title: 'Advanced Tafsir of Surah Al-Fatiha',
      description: 'Deep dive into the meanings and interpretations of the opening chapter',
      content: 'This advanced lesson explores the deeper meanings...',
      videoUrl: 'https://example.com/videos/lesson2.mp4',
      duration: 60,
      difficulty: 'advanced' as const,
      category: 'Quran',
      tags: ['Tafsir', 'Quran', 'Advanced'],
      isPremium: true,
      instructorId: 'instructor_2',
      instructorName: 'Dr. Fatima Al-Zahra',
      thumbnailUrl: '/images/lessons/lesson2-thumb.jpg',
      publishedAt: '2024-01-10T00:00:00Z',
      createdAt: '2024-01-10T00:00:00Z',
      updatedAt: '2024-01-10T00:00:00Z',
    },
    {
      id: 'lesson_3',
      title: 'Practical Application of Islamic Ethics',
      description: 'Learn how to apply Islamic ethical principles in daily life',
      content: 'This lesson focuses on practical applications...',
      videoUrl: 'https://example.com/videos/lesson3.mp4',
      duration: 30,
      difficulty: 'intermediate' as const,
      category: 'Ethics',
      tags: ['Ethics', 'Daily Life', 'Practical'],
      isPremium: false,
      instructorId: 'instructor_1',
      instructorName: 'Shaykh Ahmad Hassan',
      thumbnailUrl: '/images/lessons/lesson3-thumb.jpg',
      publishedAt: '2024-01-15T00:00:00Z',
      createdAt: '2024-01-15T00:00:00Z',
      updatedAt: '2024-01-15T00:00:00Z',
    },
  ] as Lesson[],

  analytics: {
    donations: {
      totalDonations: 248000,
      totalAmount: 248000,
      averageDonation: 86,
      monthlyDonations: [
        { month: '2024-01', count: 45, amount: 12500 },
        { month: '2024-02', count: 38, amount: 9800 },
        { month: '2024-03', count: 52, amount: 15600 },
        { month: '2024-04', count: 41, amount: 11200 },
        { month: '2024-05', count: 47, amount: 13800 },
        { month: '2024-06', count: 39, amount: 10200 },
      ],
      topCampaigns: [
        {
          campaignId: 'campaign_1',
          campaignName: 'Grand Zawiyah Construction',
          amount: 125000,
          count: 234,
        },
        {
          campaignId: 'campaign_3',
          campaignName: 'Community Support',
          amount: 78000,
          count: 189,
        },
        {
          campaignId: 'campaign_2',
          campaignName: 'Islamic Education Fund',
          amount: 45000,
          count: 156,
        },
      ],
      donorRetention: {
        newDonors: 120,
        returningDonors: 80,
        retentionRate: 0.67,
      },
    } as DonationAnalytics,
    users: {
      totalUsers: 1250,
      activeUsers: 890,
      newUsersThisMonth: 45,
      userGrowth: 0.12,
    },
    events: {
      totalEvents: 25,
      upcomingEvents: 8,
      totalRegistrations: 450,
      averageAttendance: 0.75,
    },
    lessons: {
      totalLessons: 45,
      premiumLessons: 18,
      totalViews: 12500,
      averageCompletionRate: 0.68,
    },
  },
};
